NEXT-319: Rebasing from `master` to avoid conflicts
messagemedia/documentation pull request #27
Opened 2022-10-19 22:46 UTC by SamRussellMM

- Summary v2 endpoint into Messaging Reports group
- Insight v2 endpoint into Messaging Reports group
- Schemas created for response objects.

2022-10-20 03:11 UTC, alexdia25 approved these changes

2022-10-20 03:34 UTC, liam-herbert-messagemedia requested changes

2022-10-20 03:34 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +          description: Filter results for messages that include a metadata key. If this parameter is included in the query, then either the metadata_value or metadata_values parameter must also be in
No `metadata_values` in summary reports but there is a second option to enable the `metadata_key` filter which is to _use `metadata_value` as the `group_by` option_

2022-10-20 03:34 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +          description: Filter results for messages that include a metadata key. If this parameter is included in the query, then either the metadata_value or metadata_values parameter must also be in
Same as above applies here please Sam 🙂

2022-10-20 23:38 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +          description: Filter results for messages that include a metadata key. If this parameter is included in the query, then either the metadata_value or metadata_values parameter must also be in
Hey Sam, I think this still applies as `metadata_value` can either be applied as a filter (as you have described currently) or alternatively be used as the `group_by` option.

2022-10-24 19:06 UTC, liam-herbert-messagemedia approved these changes
Nice one Sam 👍

2022-10-24 22:11 UTC, merged