NEXT-386: Fixes to async fields and summary report responses
messagemedia/documentation pull request #40
Opened 2023-01-09 21:26 UTC by SamRussellMM

Fixes to asyncfields and summaryreport's responses.

Adding 'report' as a required field, wrapping a string as an array, and expanding some schemas with missing fields.

2023-01-10 03:01 UTC, jamie-thomson-sinch approved these changes

2023-01-10 05:23 UTC, liam-herbert-messagemedia requested changes

2023-01-10 05:23 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +        scheduled_report_id:
Missing metadata object in the added properties here

2023-01-10 05:23 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +            example: [id, content, meta1]
Resolves AsyncDetailFields

2023-01-10 05:23 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +          example: detail
Metadata should appear here too per UpdateSummarySchedule

2023-01-10 05:23 UTC, liam-herbert-messagemedia commented on spec/openapi.yaml
> +        scheduled_report_id:
Will resolve UpdateDetailSchedule sheet when complete

2023-01-11 04:03 UTC, liam-herbert-messagemedia approved these changes

2023-01-11 21:43 UTC, merged